FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-build

WORKDIR /app

# Using apt-get so in the container there's a good cache of package repos
# and the space is not that much of a concern for us now
RUN    apt-get update \
    && apt-get install screen wget

ENV UDEV=on

COPY . ./

RUN    cd tools \
    && npm install

CMD ["bash", "start.sh"]
