#FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-stretch-build
# Switch to Ubuntu experimentally
FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-node:8-trusty-build

WORKDIR /app

# Using apt-get so in the container there's a good cache of package repos
# and the space is not that much of a concern for us now
RUN apt-get update \
 && apt-get install -y --no-install-recommends screen wget dosfstools mc util-linux

ENV UDEV=on

COPY . ./

RUN cd tools \
 && npm install

CMD ["bash", "start.sh"]
